### PR TITLE
Changes for kernel 6.0

### PR DESCRIPTION
**Pull request by kekrby**

### CODE REVIEW

**Comment by kekrby** [comment]
I was going to update the kernel source as well (the CI fails because of that) but I don't think the arch version of kernel 6.0 has been released yet.

**Comment by Redecorating** [comment]
ty i'll take a proper look at this once linux-6.0 gets into the arch repos

**Comment by cubercsl** [comment]
linux 6.0 is in arch testing now~

**Comment by kekrby** [comment]
I updated the patches for 6.0.2 by the way.

**Comment by Redecorating** [comment]
I've taken the first two commits for now and i'll merge the third once 6.0.2 gets into arch stable

**Pull request merged**
